name: frontend CI/CD

on:
  push:
    branches:
      - feature**
      - fix**
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun run lint
      - name: Run test
        run: bun test
        
  create-pull-request:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check and Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_ACTION_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$CURRENT_BRANCH" != "dev" ]; then
            gh pr create \
              --base dev \
              --head $CURRENT_BRANCH \
              --title "$COMMIT_MESSAGE" \
              --body "This PR is automatically created by GitHub Actions"
          else
            echo "No changes to create a PR for."
          fi
